# This workflow builds the project and deploys to NuGet.org if successful
name: Build and Deploy to NuGet
permissions:
  contents: write

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type'
        required: true
        default: 'minor'
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  version:
    name: Determine Version
    runs-on: windows-latest
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
      should_deploy: ${{ steps.version.outputs.should_deploy }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Get current version
        id: current_version
        run: |
          $version = Select-String -Path "src/SJS.DW.PrivateNugetProvider.csproj" -Pattern "<Version>(.*)</Version>" | ForEach-Object { $_.Matches.Groups[1].Value }
          echo "current_version=$version" >> $env:GITHUB_OUTPUT
          echo "Current version: $version"

      - name: Calculate new version
        id: version
        run: |
          $currentVersion = "${{ steps.current_version.outputs.current_version }}"
          $versionParts = $currentVersion.Split('.')
          $major = [int]$versionParts[0]
          $minor = [int]$versionParts[1]
          $patch = [int]$versionParts[2]
          
          $bumpType = "${{ github.event.inputs.version_bump }}"
          if ([string]::IsNullOrEmpty($bumpType)) { $bumpType = "patch" }

          switch ($bumpType) {
            "major" { $major++; $minor = 0; $patch = 0 }
            "minor" { $minor++; $patch = 0 }
            "patch" { $patch++ }
          }
          $newVersion = "$major.$minor.$patch"
          echo "new_version=$newVersion" >> $env:GITHUB_OUTPUT
          echo "should_deploy=true" >> $env:GITHUB_OUTPUT
          echo "New version: $newVersion"

      - name: Create and push tag
        run: |
          $newVersion = "${{ steps.version.outputs.new_version }}"
          git tag "v$newVersion"
          git push origin "v$newVersion"

  build:
    name: Build and Publish to NuGet
    needs: [version]
    runs-on: windows-latest
    if: always() && (needs.version.outputs.should_deploy == 'true' || github.ref_type == 'tag')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_type == 'tag' && github.ref || 'main' }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Update project version (if from version job)
        if: needs.version.outputs.new_version
        run: |
          $newVersion = "${{ needs.version.outputs.new_version }}"
          (Get-Content "src/SJS.DW.PrivateNugetProvider.csproj") -replace '<Version>.*</Version>', "<Version>$newVersion</Version>" | Set-Content "src/SJS.DW.PrivateNugetProvider.csproj"

      - name: Restore dependencies
        run: dotnet restore src/SJS.DW.PrivateNugetProvider.csproj

      - name: Build
        run: dotnet build src/SJS.DW.PrivateNugetProvider.csproj --configuration Release --no-restore

      - name: Pack
        run: |
          mkdir -p ./nupkg
          dotnet pack src/SJS.DW.PrivateNugetProvider.csproj --configuration Release --no-build --output ./nupkg --verbosity normal

      - name: List packed files (debug)
        run: |
          echo "Contents of nupkg directory:"
          Get-ChildItem -Path "./nupkg" -Force
          echo "Looking for .nupkg files:"
          Get-ChildItem -Path "./nupkg" -Filter "*.nupkg" -Recurse

      - name: Publish to NuGet.org
        run: |
          $nupkgFiles = Get-ChildItem -Path "./nupkg" -Filter "*.nupkg"
          if ($nupkgFiles.Count -eq 0) {
            Write-Error "No .nupkg files found in ./nupkg directory"
            exit 1
          }
          $firstNupkg = $nupkgFiles[0]
          echo "Publishing first package: $($firstNupkg.FullName)"
          dotnet nuget push $firstNupkg.FullName --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
